# Generated by Django 3.1.3 on 2021-06-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210610_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
    ]
