# Generated by Django 3.1.3 on 2021-06-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210611_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='avg_rating',
        ),
    ]
