# Generated by Django 3.1.3 on 2021-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210611_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating_float',
            field=models.FloatField(default=0.0),
        ),
    ]
