# Generated by Django 3.1.3 on 2021-06-17 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_product_avg_rating_float'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(help_text="Customer's Orders")),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('last_changed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPS', 'Order Placed Successfully'), ('S', 'Shipped'), ('OFD', 'Out For Delivery'), ('D', 'Delivered')], default='Order Placed Successfully', help_text='Change this only when you are sure. This sends an email to the user regarding the update.', max_length=5)),
                ('user', models.ForeignKey(help_text='User who placed this order.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
