# Generated by Django 3.1.3 on 2021-06-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210617_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
