# Generated by Django 3.1.3 on 2021-06-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_coupon_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='val',
            field=models.FloatField(default=0.0, help_text='Do NOT change this field. It gets updated automatically.'),
        ),
    ]
