# Generated by Django 3.1.3 on 2021-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20210629_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_cost',
            field=models.IntegerField(default=0),
        ),
    ]
