# Generated by Django 3.1.3 on 2021-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210702_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_applied',
            field=models.CharField(default='', max_length=20),
        ),
    ]
