# Generated by Django 3.1.3 on 2021-08-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20210802_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproduct',
            name='type_of_feature',
        ),
    ]
