# Generated by Django 3.1.3 on 2021-08-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_featuredproduct_type_of_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='featured_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.featuredcategory'),
            preserve_default=False,
        ),
    ]
