# Generated by Django 3.1.3 on 2021-08-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_featuredproduct_featured_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcategory',
            name='help_text_to_display',
            field=models.CharField(default='', max_length=200),
        ),
    ]
